### Diffusion Model

In [ ]:

Diffusion(
  (time_embedding): TimeEmbedding(
    (linear_1): Linear(in_features=320, out_features=1280, bias=True)
    (linear_2): Linear(in_features=1280, out_features=1280, bias=True)
  )
  (unet): UNet(
    (encoders): ModuleList(
      (0): SwitchSequential(
        (0): Conv2d(4, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      )
      (1-2): 2 x SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 320, eps=1e-05, affine=True)
          (conv_feature): Conv2d(320, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=320, bias=True)
          (groupnorm_merged): GroupNorm(32, 320, eps=1e-05, affine=True)
          (conv_merged): Conv2d(320, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Identity()
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 320, eps=1e-06, affine=True)
          (conv_input): Conv2d(320, 320, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=320, out_features=960, bias=False)
            (out_proj): Linear(in_features=320, out_features=320, bias=True)
          )
          (layernorm_2): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=320, out_features=320, bias=False)
            (k_proj): Linear(in_features=768, out_features=320, bias=False)
            (v_proj): Linear(in_features=768, out_features=320, bias=False)
            (out_proj): Linear(in_features=320, out_features=320, bias=True)
          )
          (layernorm_3): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=320, out_features=2560, bias=True)
          (linear_geglu_2): Linear(in_features=1280, out_features=320, bias=True)
          (conv_output): Conv2d(320, 320, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (3): SwitchSequential(
        (0): Conv2d(320, 320, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      )
      (4): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 320, eps=1e-05, affine=True)
          (conv_feature): Conv2d(320, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=640, bias=True)
          (groupnorm_merged): GroupNorm(32, 640, eps=1e-05, affine=True)
          (conv_merged): Conv2d(640, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(320, 640, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 640, eps=1e-06, affine=True)
          (conv_input): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=640, out_features=1920, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_2): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=640, out_features=640, bias=False)
            (k_proj): Linear(in_features=768, out_features=640, bias=False)
            (v_proj): Linear(in_features=768, out_features=640, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_3): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=640, out_features=5120, bias=True)
          (linear_geglu_2): Linear(in_features=2560, out_features=640, bias=True)
          (conv_output): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (5): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 640, eps=1e-05, affine=True)
          (conv_feature): Conv2d(640, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=640, bias=True)
          (groupnorm_merged): GroupNorm(32, 640, eps=1e-05, affine=True)
          (conv_merged): Conv2d(640, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Identity()
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 640, eps=1e-06, affine=True)
          (conv_input): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=640, out_features=1920, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_2): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=640, out_features=640, bias=False)
            (k_proj): Linear(in_features=768, out_features=640, bias=False)
            (v_proj): Linear(in_features=768, out_features=640, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_3): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=640, out_features=5120, bias=True)
          (linear_geglu_2): Linear(in_features=2560, out_features=640, bias=True)
          (conv_output): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (6): SwitchSequential(
        (0): Conv2d(640, 640, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      )
      (7): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 640, eps=1e-05, affine=True)
          (conv_feature): Conv2d(640, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
          (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(640, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 1280, eps=1e-06, affine=True)
          (conv_input): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=1280, out_features=3840, bias=False)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (layernorm_2): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (k_proj): Linear(in_features=768, out_features=1280, bias=False)
            (v_proj): Linear(in_features=768, out_features=1280, bias=False)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (layernorm_3): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=1280, out_features=10240, bias=True)
          (linear_geglu_2): Linear(in_features=5120, out_features=1280, bias=True)
          (conv_output): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (8): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_feature): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
          (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Identity()
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 1280, eps=1e-06, affine=True)
          (conv_input): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=1280, out_features=3840, bias=False)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (layernorm_2): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (k_proj): Linear(in_features=768, out_features=1280, bias=False)
            (v_proj): Linear(in_features=768, out_features=1280, bias=False)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (layernorm_3): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=1280, out_features=10240, bias=True)
          (linear_geglu_2): Linear(in_features=5120, out_features=1280, bias=True)
          (conv_output): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (9): SwitchSequential(
        (0): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      )
      (10-11): 2 x SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_feature): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
          (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Identity()
        )
      )
    )
    (bottleneck): SwitchSequential(
      (0): ResidualBlock(
        (groupnorm_feature): GroupNorm(32, 1280, eps=1e-05, affine=True)
        (conv_feature): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
        (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
        (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (residual_layer): Identity()
      )
      (1): AttentionBlock(
        (groupnorm): GroupNorm(32, 1280, eps=1e-06, affine=True)
        (conv_input): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
        (layernorm_1): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        (attention_1): SelfAttention(
          (in_proj): Linear(in_features=1280, out_features=3840, bias=False)
          (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (layernorm_2): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        (attention_2): CrossAttention(
          (q_proj): Linear(in_features=1280, out_features=1280, bias=False)
          (k_proj): Linear(in_features=768, out_features=1280, bias=False)
          (v_proj): Linear(in_features=768, out_features=1280, bias=False)
          (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (layernorm_3): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        (linear_geglu_1): Linear(in_features=1280, out_features=10240, bias=True)
        (linear_geglu_2): Linear(in_features=5120, out_features=1280, bias=True)
        (conv_output): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
      )
      (2): ResidualBlock(
        (groupnorm_feature): GroupNorm(32, 1280, eps=1e-05, affine=True)
        (conv_feature): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
        (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
        (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (residual_layer): Identity()
      )
    )
    (decoders): ModuleList(
      (0-1): 2 x SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 2560, eps=1e-05, affine=True)
          (conv_feature): Conv2d(2560, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
          (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(2560, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (2): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 2560, eps=1e-05, affine=True)
          (conv_feature): Conv2d(2560, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
          (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(2560, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): Upsample(
          (conv): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
      )
      (3-4): 2 x SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 2560, eps=1e-05, affine=True)
          (conv_feature): Conv2d(2560, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
          (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(2560, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 1280, eps=1e-06, affine=True)
          (conv_input): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=1280, out_features=3840, bias=False)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (layernorm_2): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (k_proj): Linear(in_features=768, out_features=1280, bias=False)
            (v_proj): Linear(in_features=768, out_features=1280, bias=False)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (layernorm_3): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=1280, out_features=10240, bias=True)
          (linear_geglu_2): Linear(in_features=5120, out_features=1280, bias=True)
          (conv_output): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (5): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 1920, eps=1e-05, affine=True)
          (conv_feature): Conv2d(1920, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=1280, bias=True)
          (groupnorm_merged): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_merged): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(1920, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 1280, eps=1e-06, affine=True)
          (conv_input): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=1280, out_features=3840, bias=False)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (layernorm_2): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (k_proj): Linear(in_features=768, out_features=1280, bias=False)
            (v_proj): Linear(in_features=768, out_features=1280, bias=False)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (layernorm_3): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=1280, out_features=10240, bias=True)
          (linear_geglu_2): Linear(in_features=5120, out_features=1280, bias=True)
          (conv_output): Conv2d(1280, 1280, kernel_size=(1, 1), stride=(1, 1))
        )
        (2): Upsample(
          (conv): Conv2d(1280, 1280, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
      )
      (6): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 1920, eps=1e-05, affine=True)
          (conv_feature): Conv2d(1920, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=640, bias=True)
          (groupnorm_merged): GroupNorm(32, 640, eps=1e-05, affine=True)
          (conv_merged): Conv2d(640, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(1920, 640, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 640, eps=1e-06, affine=True)
          (conv_input): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=640, out_features=1920, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_2): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=640, out_features=640, bias=False)
            (k_proj): Linear(in_features=768, out_features=640, bias=False)
            (v_proj): Linear(in_features=768, out_features=640, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_3): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=640, out_features=5120, bias=True)
          (linear_geglu_2): Linear(in_features=2560, out_features=640, bias=True)
          (conv_output): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (7): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 1280, eps=1e-05, affine=True)
          (conv_feature): Conv2d(1280, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=640, bias=True)
          (groupnorm_merged): GroupNorm(32, 640, eps=1e-05, affine=True)
          (conv_merged): Conv2d(640, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(1280, 640, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 640, eps=1e-06, affine=True)
          (conv_input): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=640, out_features=1920, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_2): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=640, out_features=640, bias=False)
            (k_proj): Linear(in_features=768, out_features=640, bias=False)
            (v_proj): Linear(in_features=768, out_features=640, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_3): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=640, out_features=5120, bias=True)
          (linear_geglu_2): Linear(in_features=2560, out_features=640, bias=True)
          (conv_output): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (8): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 960, eps=1e-05, affine=True)
          (conv_feature): Conv2d(960, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=640, bias=True)
          (groupnorm_merged): GroupNorm(32, 640, eps=1e-05, affine=True)
          (conv_merged): Conv2d(640, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(960, 640, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 640, eps=1e-06, affine=True)
          (conv_input): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=640, out_features=1920, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_2): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=640, out_features=640, bias=False)
            (k_proj): Linear(in_features=768, out_features=640, bias=False)
            (v_proj): Linear(in_features=768, out_features=640, bias=False)
            (out_proj): Linear(in_features=640, out_features=640, bias=True)
          )
          (layernorm_3): LayerNorm((640,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=640, out_features=5120, bias=True)
          (linear_geglu_2): Linear(in_features=2560, out_features=640, bias=True)
          (conv_output): Conv2d(640, 640, kernel_size=(1, 1), stride=(1, 1))
        )
        (2): Upsample(
          (conv): Conv2d(640, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
      )
      (9): SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 960, eps=1e-05, affine=True)
          (conv_feature): Conv2d(960, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=320, bias=True)
          (groupnorm_merged): GroupNorm(32, 320, eps=1e-05, affine=True)
          (conv_merged): Conv2d(320, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(960, 320, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 320, eps=1e-06, affine=True)
          (conv_input): Conv2d(320, 320, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=320, out_features=960, bias=False)
            (out_proj): Linear(in_features=320, out_features=320, bias=True)
          )
          (layernorm_2): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=320, out_features=320, bias=False)
            (k_proj): Linear(in_features=768, out_features=320, bias=False)
            (v_proj): Linear(in_features=768, out_features=320, bias=False)
            (out_proj): Linear(in_features=320, out_features=320, bias=True)
          )
          (layernorm_3): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=320, out_features=2560, bias=True)
          (linear_geglu_2): Linear(in_features=1280, out_features=320, bias=True)
          (conv_output): Conv2d(320, 320, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (10-11): 2 x SwitchSequential(
        (0): ResidualBlock(
          (groupnorm_feature): GroupNorm(32, 640, eps=1e-05, affine=True)
          (conv_feature): Conv2d(640, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (linear_time): Linear(in_features=1280, out_features=320, bias=True)
          (groupnorm_merged): GroupNorm(32, 320, eps=1e-05, affine=True)
          (conv_merged): Conv2d(320, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (residual_layer): Conv2d(640, 320, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): AttentionBlock(
          (groupnorm): GroupNorm(32, 320, eps=1e-06, affine=True)
          (conv_input): Conv2d(320, 320, kernel_size=(1, 1), stride=(1, 1))
          (layernorm_1): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (attention_1): SelfAttention(
            (in_proj): Linear(in_features=320, out_features=960, bias=False)
            (out_proj): Linear(in_features=320, out_features=320, bias=True)
          )
          (layernorm_2): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (attention_2): CrossAttention(
            (q_proj): Linear(in_features=320, out_features=320, bias=False)
            (k_proj): Linear(in_features=768, out_features=320, bias=False)
            (v_proj): Linear(in_features=768, out_features=320, bias=False)
            (out_proj): Linear(in_features=320, out_features=320, bias=True)
          )
          (layernorm_3): LayerNorm((320,), eps=1e-05, elementwise_affine=True)
          (linear_geglu_1): Linear(in_features=320, out_features=2560, bias=True)
          (linear_geglu_2): Linear(in_features=1280, out_features=320, bias=True)
          (conv_output): Conv2d(320, 320, kernel_size=(1, 1), stride=(1, 1))
        )
      )
    )
  )
  (final): FinalLayer(
    (groupnorm): GroupNorm(32, 320, eps=1e-05, affine=True)
    (conv): Conv2d(320, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
)

In [2]:
import torch
timesteps=torch.linspace(999,0,50)
timesteps

tensor([999.0000, 978.6122, 958.2245, 937.8367, 917.4490, 897.0612, 876.6735,
        856.2857, 835.8979, 815.5102, 795.1224, 774.7347, 754.3469, 733.9592,
        713.5714, 693.1837, 672.7959, 652.4082, 632.0204, 611.6327, 591.2449,
        570.8572, 550.4694, 530.0817, 509.6939, 489.3061, 468.9184, 448.5306,
        428.1429, 407.7551, 387.3673, 366.9796, 346.5918, 326.2041, 305.8163,
        285.4286, 265.0408, 244.6530, 224.2653, 203.8775, 183.4898, 163.1020,
        142.7143, 122.3265, 101.9388,  81.5510,  61.1633,  40.7755,  20.3878,
          0.0000])

In [3]:
999.0000-978.6122

20.38779999999997

In [4]:
978.6122-958.2245

20.387699999999995

In [5]:
958.2245-937.8367

20.387800000000084

In [6]:
81.5510-61.1633

20.387700000000002

In [7]:
import torch
dtype=torch.float32

In [13]:
x=torch.arange(start=0, end=5, dtype=dtype) / 5

In [14]:
x

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000])

In [15]:
len(x)

5

In [16]:
freqs=torch.pow(10000,-torch.arange(start=0, end=5, dtype=dtype) / 5)

In [18]:
freqs

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])

In [20]:
import numpy as np

In [21]:
timestep = np.float64(999.0)

In [22]:
import torch

In [24]:
torch.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [28]:
torch.pow(10,-torch.arange(0,5)/5)

tensor([1.0000, 0.6310, 0.3981, 0.2512, 0.1585])

In [ ]:
dtype=torch.float32
# torch.pow(10,-torch.arange(0,5,dtype=dtype)/5)

tensor([1.0000, 0.6310, 0.3981, 0.2512, 0.1585])

In [33]:
x=-torch.arange(0,5,dtype=dtype)/5

In [34]:
x

tensor([-0.0000, -0.2000, -0.4000, -0.6000, -0.8000])

In [35]:
freqs=torch.pow(10,x)

In [36]:
freqs

tensor([1.0000, 0.6310, 0.3981, 0.2512, 0.1585])

In [45]:
x=torch.tensor([2])
x.shape
x1=x[:,None]
x1

tensor([[2]])

### torch切片

In [39]:
import torch

# 创建一个 3D 张量
tensor = torch.arange(27).reshape(3, 3, 3)
print(tensor)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


In [41]:
#单维度切片
#选择第0维，索引为1
x=tensor[1]
x

tensor([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [42]:
#多维度切片
# 选择前两层（0 和 1），所有行，列取 0 和 1
result = tensor[:2, :, :2]
print(result)

tensor([[[ 0,  1],
         [ 3,  4],
         [ 6,  7]],

        [[ 9, 10],
         [12, 13],
         [15, 16]]])


In [46]:
x = torch.tensor([1, 2, 3])  # 一维张量
print("原张量 x：", x)
print("形状：", x.shape)  # torch.Size([3])

原张量 x： tensor([1, 2, 3])
形状： torch.Size([3])


In [47]:
x_expanded = x[:, None]
print("扩展后的张量 x_expanded：\n", x_expanded)
print("形状：", x_expanded.shape)  # torch.Size([3, 1])


扩展后的张量 x_expanded：
 tensor([[1],
        [2],
        [3]])
形状： torch.Size([3, 1])


In [48]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])

In [49]:
result_dim0 = torch.cat([a, b], dim=0)
print(result_dim0)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [51]:
result_dim1 = torch.cat([a, b], dim=-1)
print(result_dim1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


In [1]:
ls=[ 1,  2,  3,  7,  8,  9]

In [2]:
ls+=[10,11]

In [3]:
ls

[1, 2, 3, 7, 8, 9, 10, 11]

In [4]:
ls+=[0,-1]*2

In [5]:
ls

[1, 2, 3, 7, 8, 9, 10, 11, 0, -1, 0, -1]

In [1]:
999-978.6122449 

20.38775510000005

In [2]:
978.6122449-958.2244898

20.387755099999936